import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:shoesque/cubit/cubit.dart';
import 'package:shoesque/models/models.dart';
import 'package:shoesque/ui/widgets/widgets.dart';
import 'package:supercharged/supercharged.dart';
import 'package:flutter/cupertino.dart';
import 'package:shoesque/shared/share.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:get/get.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'general_page.dart';
part 'sign_in_page.dart';
part 'sign_up_page.dart';
part 'address_page.dart';
part 'mainpage.dart';
part 'shoes_page.dart';
part 'shoes_details.dart';
part 'payment_page.dart';
part 'ilustration_page.dart';
part 'success_page.dart';
part 'succes_sigup_page.dart';
part 'order_history.dart';
part 'profile.dart';
